logging:
  level: INFO
  appenders:
    - type: console

swagger:
  resourcePackage: com.expedia.www.doppler.metastore.service.resources
  schemes:
    - http

database:
  driverClass: org.postgresql.Driver
  user: xxxxxxx
  password: xxxxxxx
  url: jdbc:postgresql://localhost:5432/doppler_metastore
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: update
    hibernate.show_sql: true

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

server:
  applicationConnectors:
      - type: http
        port: 8080
  adminConnectors:
      - type: http
        port: 8081

httpClientConfiguration:
  timeout: 1000ms
  connectionTimeout: 1000ms
  timeToLive: 1 hour
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0s
  minThreads: 1
  maxThreads: 128
  gzipEnabled: true
  gzipEnabledForRequests: true
  retries: 3

searchServiceURI: xxxxxxxxxxxxxxxxxxxxxxxx
